# Generated by Django 4.2.10 on 2024-04-04 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='My_collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('nomer', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер')),
                ('nomer_dliy_otobrajeniy', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер порядковый для сайта')),
                ('nominal', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номинал')),
                ('rubrika', models.CharField(blank=True, max_length=200, null=True, verbose_name='Рубрика')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('opisanie', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('seria', models.CharField(blank=True, choices=[('Cпорт', 'Cпорт'), ('Cвязь', 'Cвязь'), ('Фауна', 'Фауна'), ('Флора', 'Флора'), ('Стандарт', 'Стандарт'), ('Военная', 'Военная'), ('История', 'История'), ('Культура', 'Культура'), ('Техника', 'Техника'), ('Космос', 'Космос'), ('Заповедники', 'Заповедники'), ('География', 'География')], default='', max_length=200, null=True, verbose_name='Серия')),
                ('pod_seria', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Подсерия')),
                ('blok', models.CharField(blank=True, max_length=200, null=True, verbose_name='Блок/Номер')),
                ('pechat', models.CharField(blank=True, max_length=200, null=True, verbose_name='Печать')),
                ('bumaga', models.CharField(blank=True, max_length=200, null=True, verbose_name='Бумага')),
                ('perforaciy', models.CharField(blank=True, max_length=200, null=True, verbose_name='Перфорация')),
                ('cena_chist_katalog', models.CharField(blank=True, max_length=30, null=True, verbose_name='Цена чистая каталог (Загорский')),
                ('cena_chist_meshoc', models.CharField(blank=True, max_length=30, null=True, verbose_name='Цена чистой (Мешок')),
                ('razmer', models.CharField(blank=True, max_length=30, null=True, verbose_name='Размер')),
                ('tiraj', models.IntegerField(blank=True, null=True, verbose_name='Тираж')),
                ('nalichie', models.CharField(blank=True, max_length=150, null=True, verbose_name='Наличие марки/блока')),
                ('listu', models.CharField(blank=True, max_length=150, null=True, verbose_name='Наличие листов')),
                ('malue_listu', models.CharField(blank=True, max_length=150, null=True, verbose_name='Наличие малых листов')),
                ('raznovidnost', models.CharField(blank=True, max_length=150, null=True, verbose_name='Наличие разновидности')),
                ('suvenirnuy_nabor_oblojki', models.CharField(blank=True, max_length=150, null=True, verbose_name='Наличие сувенирного набора')),
                ('marochnuy_buklet', models.CharField(blank=True, max_length=150, null=True, verbose_name='Наличие марочного буклета')),
                ('podarochnuy_nabor', models.CharField(blank=True, max_length=150, null=True, verbose_name='Наличие подарочного набора')),
                ('goda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='my_collection.goda')),
            ],
        ),
    ]
