# Generated by Django 5.0.3 on 2024-04-08 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_collection',
            name='goda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blog_posts', to='my_collection.goda'),
        ),
    ]
